name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        env:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: classic
          config_timezone: America/Santo_Domingo
          plugin_languages: yes
          plugin_activity: yes
          plugin_isocalendar: yes
