name: WakaTime Update

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta todos los días a medianoche UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
